tclean(vis='2018pipeline_11.ms.contsub',
    imagename='NH3_11',
    spw='0',
    field='0',
    specmode='cube',
    start='0.0km/s',
    width='0.1km/s',
    restfreq='23.69447GHz',
    deconvolver='multiscale',
    scales=[0,3,9],
    pbmask=0.2, threshold='3mJy',
    imsize=[200,200],
    restoringbeam='common',
    niter=int(1e6),
    #AUTOMASK PARAMETERS BELOW
    usemask='auto-multithresh',
    noisethreshold=.0,
    sidelobethreshold=1.2, 
    minbeamfrac=0.3,
    lownoisethreshold=1.0, 
    negativethreshold=4.0)

tclean(vis='2018pipeline_22.ms.contsub',
    imagename='NH3_22',
    spw='0',
    field='0',
    specmode='cube',
    start='0.0km/s',
    width='0.2km/s',
    restfreq='23.72260GHz',
    deconvolver='multiscale',
    scales=[0,3,9],
    pbmask=0.2, threshold='2.5mJy',
    imsize=[200,200],
    restoringbeam='common',
    niter=int(1e6),
    #AUTOMASK PARAMETERS BELOW
    usemask='auto-multithresh',
    noisethreshold=5.0,
    sidelobethreshold=1.25, 
    minbeamfrac=0.3,
    lownoisethreshold=1.0, 
    negativethreshold=4.0)

tclean(vis='2018pipeline_33.ms.contsub',
    imagename='NH3_33',
    spw='0', 
    field='0',
    specmode='cube',
    start='0.0km/s',
    width='0.1km/s',
    restfreq='23.87008GHz',
    deconvolver='multiscale', scales=[0,3,9],
    pbmask=0.2,
    threshold='2mJy',
    imsize=[250,250],
    restoringbeam='common',
    niter=int(1e6),
    #AUTOMASK PARAMETERS BELOW
    usemask='auto-multithresh',
    noisethreshold=5.0,
    sidelobethreshold=1.25, 
    minbeamfrac=0.3, 
    lownoisethreshold=2.0, 
    negativethreshold=5.0) 

tclean(vis='2018pipeline_44.ms.contsub',
       imagename='NH3_44',
       spw='0',
       field='0',
       specmode='cube',
       start='0.0km/s',
       width='0.1km/s',
       restfreq='24.13935GHz',
       deconvolver='multiscale', 
       scales=[0,3,9],
       mask='4-4_mask_04.mask',
       threshold=0.0001,
       imsize=[200,200],
       restoringbeam='common',
       niter=50000)

tclean(vis='2018pipeline_55.ms.contsub',
       imagename='NH3_55',
       spw='0',
       field='0',
       specmode='cube',
       start='0.0km/s',
       width='0.1km/s',
       restfreq='24.53292GHz',
       deconvolver='multiscale',
       scales=[0,3,9],
       mask='5-5_mask_04.mask',
       pbmask=0.2,
       threshold=0.0004,
       imsize=[200,200],
       restoringbeam='common',
       niter=50000)
